name: Artifact Demo

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -run:
        mkdir temp
        echo "alpha" > temp/alpha.html

    - uses: action/upload-Artifact@v4
    with:
      name:files
      path:temp/
